<a href="https://colab.research.google.com/github/AlexanderLyuft/Fake_math/blob/main/%D0%98%D1%81%D1%82%D0%BE%D1%80%D0%B8%D1%8F_%D0%B8_%D1%80%D0%B0%D0%B7%D0%B2%D0%B8%D1%82%D0%B8%D0%B5_%D0%98%D0%98_%D0%94_%D0%97.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Пример кода для многослойного персептрона, чтобы решить задачу XOR:

In [2]:
import numpy as np

# Сигмоидная функция и её производная
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# Данные для XOR
X = np.array([[0, 0],
              [0, 1],
              [1, 0],
              [1, 1]])

y = np.array([[0], [1], [1], [0]])

# Параметры
input_layer_neurons = 2  # количество входов
hidden_layer_neurons = 2  # количество нейронов в скрытом слое
output_neurons = 1        # количество выходов
learning_rate = 0.5
epochs = 10000

# Инициализация весов
np.random.seed(42)  # для воспроизводимости
hidden_weights = np.random.uniform(size=(input_layer_neurons, hidden_layer_neurons))
output_weights = np.random.uniform(size=(hidden_layer_neurons, output_neurons))

for _ in range(epochs):
    # Прямое распространение
    hidden_layer_activation = np.dot(X, hidden_weights)
    hidden_layer_output = sigmoid(hidden_layer_activation)

    output_layer_activation = np.dot(hidden_layer_output, output_weights)
    predicted_output = sigmoid(output_layer_activation)

    # Обратное распространение ошибки
    error = y - predicted_output
    d_predicted_output = error * sigmoid_derivative(predicted_output)

    output_weights += hidden_layer_output.T.dot(d_predicted_output) * learning_rate
    d_hidden_layer = d_predicted_output.dot(output_weights.T) * sigmoid_derivative(hidden_layer_output)
    hidden_weights += X.T.dot(d_hidden_layer) * learning_rate

print("Обучение завершено. Предсказанный вывод для XOR:")
print(predicted_output)

Обучение завершено. Предсказанный вывод для XOR:
[[0.05432236]
 [0.89824713]
 [0.89824729]
 [0.13513498]]


Код для однослойного персептрона, который будет пытаться решить задачу XOR. Из-за линейной неразделимости этой задачи, однослойный персептрон не сможет добиться хороших результатов.

In [3]:
import numpy as np

# Сигмоидная функция и её производная
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# Данные для XOR
X = np.array([[0, 0],
              [0, 1],
              [1, 0],
              [1, 1]])

y = np.array([[0], [1], [1], [0]])

# Параметры
input_layer_neurons = 2  # количество входов
output_neurons = 1        # количество выходов
learning_rate = 0.5

# Инициализация весов
np.random.seed(42)  # для воспроизводимости
weights = np.random.uniform(size=(input_layer_neurons, output_neurons))

# Обучение персептрона на 10 000, 20 000 и 50 000 эпох
for epochs in [10000, 20000, 50000]:
    for _ in range(epochs):
        # Прямое распространение
        output = sigmoid(np.dot(X, weights))

        # Обратное распространение ошибки
        error = y - output
        d_output = error * sigmoid_derivative(output)
        weights += X.T.dot(d_output) * learning_rate

    print(f"Результат после {epochs} эпох:")
    print(output)

Результат после 10000 эпох:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Результат после 20000 эпох:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
Результат после 50000 эпох:
[[0.5]
 [0.5]
 [0.5]
 [0.5]]


Вывод об однослойных и многослойных персептронах

Однослойный персептрон способен решать только линейно разделимые задачи. В случае задачи XOR, где входы не могут быть разделены линейной функцией, однослойный персептрон не дает хороших результатов при обучении.

Многослойный персептрон, благодаря наличию скрытых слоев, способен моделировать нелинейные зависимости и успешно решать такие задачи, как XOR. Он использует несколько слоев нейронов, которые применяют нелинейные функции активации, что позволяет ему находить сложные зависимости в данных.
Таким образом, многослойные персептроны являются более мощными инструментами для решения различных задач в сравнении с однослойными персептронами.